// ______________________________________________________________

// Assignment: Chapter 27 (Random Numbers)
// ______________________________________________________________

// // Q1
// Convert a random number generated by JavaScript to a number in
// the range 1 to 50

// var y = Math.random();
// console.log(y*50);

// // Q2
// Generate a random number and assign it to a variable that hasn't
// been declared beforehand.

// var y = Math.random();
// var x = y;
// console.log(x);

// // Q3
// You have to create a dice in JavaScript with the use of 
// pseudorandom number.

// var y = Math.random();
// var dicevalue =Math.ceil(y*6);
// console.log(dicevalue);


// // Q4
// You have to create a toss (head/tail) in JavaScript with the use of
// pseudo-random number


// var y = Math.random();
// var toss =Math.round(y);
// console.log(toss)
// if(toss==true){
// 	document.write("Head");
// }
// else{
// 	document.write("Tail");
// }